'use strict';
// Browser-level acceptance against an isolated real server and real renderer.
const fs = require('node:fs');
const os = require('node:os');
const path = require('node:path');
const assert = require('node:assert/strict');
const { chromium } = require('playwright');
const { createApp } = require('../server');
(async () => {
  const root=fs.mkdtempSync(path.join(os.tmpdir(),'pipeline-ui-'));
  const evidence=path.resolve(__dirname,'..','data','qa'); fs.mkdirSync(evidence,{recursive:true});
  const app=createApp({dataDir:path.join(root,'data'),projectsDir:path.join(root,'projects'),autoFetch:false});
  const server=await new Promise(resolve=>{const s=app.listen(0,'127.0.0.1',()=>resolve(s));});
  const base=`http://127.0.0.1:${server.address().port}`;
  const browser=await chromium.launch({headless:true});
  const page=await browser.newPage({viewport:{width:1440,height:1100}});
  const errors=[], failed=[], steps=[];
  page.on('pageerror',e=>errors.push(e.message));
  page.on('response',r=>{if(r.status()>=400 && !r.url().endsWith('/favicon.ico'))failed.push(`${r.status()} ${r.url()}`);});
  page.on('dialog',d=>d.accept());
  const click=action=>page.locator(`[data-action="${action}"]:visible`).first().click();
  const save=async(action,part,method='POST')=>{const response=page.waitForResponse(r=>r.url().includes(part)&&r.request().method()===method);await action();const r=await response;assert.ok(r.ok(),`${r.status()} ${await r.text()}`);return r.json();};
  const nav=async name=>{await page.locator(`.aura-nav-item[data-p="${name}"]`).click();await page.locator(`#p-${name}.on`).waitFor();};
  try {
    await page.goto(base,{waitUntil:'domcontentloaded'});
    await page.waitForFunction(()=>document.querySelector('#ctxt')?.textContent.includes('已连接'));
    await page.screenshot({path:path.join(evidence,'overview-desktop.png'),fullPage:true});
    await nav('matrix');
    await page.fill('#it','本地端到端验收'); await page.fill('#id2','从热点到可播放的视频。\n保存真实内容，再查看制作结果。');
    await save(()=>page.locator('#idea-form button[type="submit"], #idea-submit').first().click(),'/api/data');
    await page.locator('[data-action="build-idea"]').first().waitFor(); await click('build-idea');
    await page.locator('#studio-title').waitFor();
    await page.fill('#studio-plan','从热点到可播放的视频。\n保存真实内容，再查看制作结果。');
    await page.locator('[data-action="studio-tab"][data-tab="scenes"]').click();
    await save(()=>click('generate-draft'),'/generate-blueprint');
    await page.locator('.scene-title').first().waitFor();
    assert.equal(await page.locator('.scene-title').count(),2);
    for(const input of await page.locator('.scene-duration').all())await input.fill('2');
    await save(()=>click('save-studio'),'/content','PUT');
    await save(()=>click('render-studio'),'/projects/render');
    // Reload while the real job is running: the UI must recover job and project.
    await page.reload({waitUntil:'domcontentloaded'});
    await page.waitForSelector('#studio-media video',{timeout:120000});
    await page.waitForFunction(()=>{const v=document.querySelector('#studio-media video');return v&&v.readyState>=1&&v.videoWidth>0;});
    const media=await page.locator('#studio-media video').evaluate(v=>({width:v.videoWidth,height:v.videoHeight,duration:v.duration}));
    assert.equal(media.width,720);assert.equal(media.height,1280);assert.ok(Math.abs(media.duration-4)<.2);
    await page.locator('#studio-media video').evaluate(v=>v.play());
    await page.waitForFunction(()=>document.querySelector('#studio-media video').currentTime>.15);
    const [download]=await Promise.all([page.waitForEvent('download'),page.locator('#studio-downloads [data-action="download"][data-kind="video"]').click()]);await download.saveAs(path.join(evidence,'browser-downloaded.mp4'));
    steps.push('新建选题→保存内容→生成分镜→真实渲染→刷新恢复→实际播放→下载');
    await page.locator('[data-action="studio-tab"][data-tab="cover"]').click();
    await page.locator('[data-field="TITLE_LINE_1"]').fill('封面编辑已验证');
    await save(()=>page.locator('#studio-cover-form button').click(),'/update-cover');
    await save(()=>click('archive-studio'),'/archive');
    await page.screenshot({path:path.join(evidence,'studio-desktop.png'),fullPage:true});
    steps.push('重复封面字段编辑与已验证成片归档');
    await click('schedule-studio');
    await page.selectOption('#pp','both');await page.selectOption('#ps','published');
    await save(()=>page.locator('#calendar-form button').first().click(),'/api/data');
    await nav('overview');await page.selectOption('#qe-pick',{index:1});await page.fill('#qe-dy-v','123');await page.fill('#qe-dy-c','42.5');
    await save(()=>page.locator('#quick-review-form button').click(),'/api/data');
    await nav('review');await page.fill('#wn','验收记录：真实浏览器流程完成。');
    await save(()=>page.locator('#note-form button').click(),'/api/data');
    await page.locator('#notes-box').getByText('验收记录：真实浏览器流程完成。').waitFor();
    await page.fill('#sw','本地创作');await page.fill('#swc','5');await save(()=>page.locator('#keyword-form button').click(),'/api/data');
    await page.screenshot({path:path.join(evidence,'review-desktop.png'),fullPage:true});
    steps.push('关联人工发布→快速录入实际测试指标→笔记与搜索词保存');
    await nav('hot');await page.fill('#hi','<img src=x onerror="window.__xss=1">');await save(()=>page.locator('#hot-form button').click(),'/api/data');
    assert.equal(await page.evaluate(()=>window.__xss),undefined);
    await click('brief');await page.locator('#brief-box:not([hidden])').waitFor();
    await nav('playbook');await nav('assets');await nav('settings');
    const [backup]=await Promise.all([page.waitForEvent('download'),click('export-data')]);await backup.saveAs(path.join(evidence,'ui-backup.json'));
    const backupData=JSON.parse(fs.readFileSync(path.join(evidence,'ui-backup.json'),'utf8'));assert.equal(backupData.collections.ideas.length,1);assert.equal(backupData.collections.reviews.length,1);
    await page.getByTitle('Toggle theme').click();
    await nav('overview');await page.screenshot({path:path.join(evidence,'overview-dark.png'),fullPage:true});
    await page.setViewportSize({width:390,height:844});
    await page.mouse.move(389,843);
    await page.screenshot({path:path.join(evidence,'overview-mobile.png'),fullPage:true});
    assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1),'移动端产生横向溢出');
    steps.push('脚本注入边界、页面切换、备份下载、主题与移动端布局');
    assert.deepEqual(errors,[],'浏览器脚本错误');assert.deepEqual(failed,[],'浏览器HTTP错误');
    const report={at:new Date().toISOString(),steps,media,errors,failed};fs.writeFileSync(path.join(evidence,'ui-evidence.json'),JSON.stringify(report,null,2));console.log(JSON.stringify(report,null,2));
  } catch(error) {
    await page.screenshot({path:path.join(evidence,'ui-failure.png'),fullPage:true}).catch(()=>{});
    console.error(JSON.stringify({errors,failed,url:page.url()},null,2));throw error;
  } finally {await browser.close();await app.locals.close();await new Promise(resolve=>server.close(resolve));fs.rmSync(root,{recursive:true,force:true});}
})().catch(error=>{console.error(error);process.exitCode=1;});
